### PR TITLE
some 10-10.3.3 offsets

### PR DESCRIPTION
**Pull request by Mila432**

### CODE REVIEW

**Comment by Siguza** [comment]
I appreciate this, but I'm not gonna pull just yet - required offsets might still change. I'll leave the pull request open though.

**Comment by christianloopp** [comment]
@Mila432 I'd also like to note that some of the offsets are wrong. Also, I've noticed before that some devices/versions might have the same uname version so it'll cause issues in the future.

**Comment by Mila432** [comment]
@Siguza  I will keep an eye on this
@iabem97 what device group iPhones or iPads ? What offsets are wrong so I can improve my script

**Comment by hbouhadji** [comment]
@Mila432 iPhone 6S 10.3.3, I didn't find the same offsets

**Comment by Mila432** [comment]
@Hakim-Bou  whats the darwin kernel version?

**Comment by GreenSeed** [comment]
@Mila432  pls give me offsets for Darwin Kernel Version 16.7.0: Thu Jun 15 18:33:36 PDT 2017; root:xnu-3789.70.16~4/RELEASE_ARM64_S8000 (iphone 6s ios 10.3.3)

**Comment by Samgisaninja** [comment]
@GreenSeed 

```
"iPhone8,1":
        {
          "10.3.3":
            {
              "OFFSET_ZONE_MAP": "0xfffffff007548478",
              "OFFSET_KERNEL_MAP": "0xfffffff0075a4050",
              "OFFSET_KERNEL_TASK": "0xfffffff0075a4048",
              "OFFSET_REALHOST": "0xfffffff00752aba0",
              "OFFSET_BZERO": "0xfffffff007081f80",
              "OFFSET_BCOPY": "0xfffffff007081dc0",
              "OFFSET_COPYIN": "0xfffffff0071803a0",
              "OFFSET_COPYOUT": "0xfffffff007180594",
              "OFFSET_IPC_PORT_ALLOC_SPECIAL": "0xfffffff007099e94",
              "OFFSET_IPC_KOBJECT_SET": "0xfffffff0070ad16c",
              "OFFSET_IPC_PORT_MAKE_SEND": "0xfffffff0070999b8",
              "OFFSET_IOSURFACEROOTUSERCLIENT_VTAB": "0xfffffff006f25538",
              "OFFSET_ROP_ADD_X0_X0_0X10": "0xfffffff006462174"
            }
        }
```

**Comment by Rybo713** [comment]
Is this the right offset for:

iPhone 6s+

iOS 10.3.3 (14G60) 

Darwin Kernel Version 16.7.0:Thu Jun 15 18:33:36 PDT 2017; root:xnu-3789.70.16~4/RELEASE_ARM64_S8000

0xfffffff007081f80 OFFSET_BZERO
0xfffffff007081dc0 OFFSET_BCOPY
0xfffffff0071803a0 OFFSET_COPYIN
0xfffffff007180594 OFFSET_COPYOUT
0xfffffff0075a4050 OFFSET_KERNEL_MAP
0xfffffff0075a4048 OFFSET_KERNEL_TASK
0xfffffff007548478 OFFSET_ZONE_MAP
0xfffffff00752aba0 OFFSET_REALHOST
0xfffffff0070999b8 OFFSET_IPC_PORT_MAKE_SEND
0xfffffff0070ad16c OFFSET_IPC_KOBJECT_SET
0xfffffff007099e94OFFSET_IPC_PORT_ALLOC_SPECIAL
OFFSET_IOSURFACEROOTUSERCLIENT_VTAB
0xfffffff006e7b9c8
0xfffffff006462174 OFFSET_ROP_ADD_X0_X0_10

**Pull request closed without merging**
