### PR TITLE
Consolidate offsets

### PR DESCRIPTION
**Pull request by UInt2048**
UNTESTED commit to remove final struct offsets. Please adjust if this commit wrongly alters `sizeof` operations.

### CODE REVIEW

**Comment by Siguza** [comment]
This invokes undefined behaviour, and I'd bet money that it will corrupt the stack too:

```c
union
{
    struct
    {
        mach_vm_address_t addr1;
        mach_vm_address_t addr2;
        uint32_t id;
    } data;
} surface;
size_t size = off->iosurface_create_outsize;
VOLATILE_BZERO32(&surface, size);
ret = IOConnectCallStructMethod(client, IOSURFACE_CREATE_SURFACE, dict_create, sizeof(dict_create), &surface, &size);
```

Removing the other union member makes the stack allocation a lot smaller... which is the entire reason it was there in the first place.

**Comment by UInt2048** [comment]
Alright, I guess I'll close this PR. By the way, how did you determine the IOSurface create outsize offset?

**Comment by Siguza** [comment]
`IOSurfaceRootUserClient::externalMethod()` references a table of `IOExternalMethodDispatch` objects, which contains the required in and out struct sizes.

**Comment by UInt2048** [comment]
Thank you, I managed to find the IOExternalMethodDispatch structs in the IOSurfaceRootUserClient vtable after a little under 0x100 addresses

**Pull request closed without merging**
