### PR TITLE
doc improvements

### PR DESCRIPTION
**Pull request by 0-vortex**
couple of typos and some spacing

### CODE REVIEW

**Comment by ghost** [comment]
you should've just submitted an issue instead of a pull request for clout

**Comment by 0-vortex** [comment]
Maybe don't come asking for proofreading on twitter then. 
Thumbs down for what ? Spending time reading this and actually contributing something ?

**Comment by Siguza** [comment]
Alright, I'm in the process of updating my write-up. I appreciate the typo fixed and will incorporate them, but what's the deal with spaces before question marks, and with the changed paragraphs that seems to lack actual changes though?

**Comment by 0-vortex** [comment]
inconsistent line endings and removed byte order mark, you can diff that in the terminal, suppose that's something only windows users are affected by

**Comment by danpham304** [comment]
Bkd

**Comment by nliz77** [comment]
Nice

**Pull request closed without merging**
